import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# ===============================================================
# Step 1: Load result CSV files generated by the C++ program
# ===============================================================
# Assumes the following files exist in the same directory
try:
    df_15 = pd.read_csv("results_PPR_alpha_15.csv")
    df_50 = pd.read_csv("results_PPR_alpha_50.csv")
    df_85 = pd.read_csv("results_PPR_alpha_85.csv")
except FileNotFoundError:
    print("Error: CSV files not found! Make sure you ran the C++ code.")
    exit()

# ===============================================================
# Step 2: Select the top 10 suspicious nodes
# The ranking is based on Alpha = 0.15 (baseline configuration)
# ===============================================================
top_nodes = df_15.head(10)['NodeID'].tolist()

# ===============================================================
# Step 3: Retrieve suspicion scores of the same nodes
# from other alpha configurations
# ===============================================================
scores_15 = df_15[df_15['NodeID'].isin(top_nodes)]['Score'].tolist()
scores_50 = []
scores_85 = []

for node in top_nodes:
    # Find the score of the same node in other result files
    s50 = df_50[df_50['NodeID'] == node]['Score'].values
    s85 = df_85[df_85['NodeID'] == node]['Score'].values
    
    scores_50.append(s50[0] if len(s50) > 0 else 0)
    scores_85.append(s85[0] if len(s85) > 0 else 0)

# ===============================================================
# Step 4: Plot grouped bar chart for sensitivity analysis
# ===============================================================
x = np.arange(len(top_nodes))
width = 0.25

plt.figure(figsize=(12, 6))

plt.bar(
    x - width,
    scores_15,
    width,
    label='Alpha = 0.15 (Standard)',
    color='skyblue'
)

plt.bar(
    x,
    scores_50,
    width,
    label='Alpha = 0.50',
    color='orange'
)

plt.bar(
    x + width,
    scores_85,
    width,
    label='Alpha = 0.85 (High Damping)',
    color='salmon'
)

# Chart formatting
plt.xlabel('Top Suspicious Nodes')
plt.ylabel('Suspicion Score')
plt.title('Parameter Sensitivity Analysis: Effect of Alpha on Scores')
plt.xticks(x, top_nodes, rotation=45)
plt.legend()
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Adjust layout and save figure
plt.tight_layout()
plt.savefig('plot_sensitivity.png')
plt.show()
